export const CHANGE_CURRENCY = "CHANGE_CURRENCY"
export const GET_CURRENCIES = "GET_CURRENCIES" 
export const GET_CURRENCIES_SUCCESS ="GET_CURRENCIES_SUCCESS"
export const GET_CURRENCIES_FAILED = "GET_CURRENCIES_FAILED"