export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"
export const GET_PRODUCT__DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS" 
export const GET_PRODUCTS_DETAILS_FAILURE = "GET_PRODUCT_DETAILS_FAILURE" 
